import { NextRequest, NextResponse } from 'next/server'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { imageUrl, prompt } = body

    if (!imageUrl || typeof imageUrl !== 'string' || imageUrl.trim().length === 0) {
      return NextResponse.json(
        { success: false, error: 'Image URL is required' },
        { status: 400 }
      )
    }

    const ZAI = (await import('z-ai-web-dev-sdk')).default
    const client = await ZAI.create()

    const analysisPrompt = prompt || `تحلیل جامع این تصویر ارائه بده به فارسی:
1. **توضیحات تصویر** - شرح دقیق محتوای تصویر
2. **عناصر کلیدی** - اشیاء، افراد، مکان‌ها و رنگ‌های اصلی
3. **متن قابل خواندن** - هر متنی در تصویر
4. **کیفیت بصری** - ارزیابی کیفیت (۱ تا ۱۰)
5. **پیشنهاد Alt Text** - متن جایگزین SEO-friendly
6. **کاربردها** - بهترین استفاده‌های ممکن از این تصویر
7. **بهبودها** - پیشنهادات بهبود تصویر

از Markdown برای فرمت‌بندی استفاده کن.`

    const response = await client.chat.completions.createVision({
      messages: [
        {
          role: 'user',
          content: [
            { type: 'text', text: analysisPrompt },
            {
              type: 'image_url',
              image_url: {
                url: imageUrl.startsWith('data:') ? imageUrl : imageUrl,
              },
            },
          ],
        },
      ],
      thinking: { type: 'disabled' },
    })

    const analysisText = response.choices[0]?.message?.content

    if (!analysisText) {
      return NextResponse.json(
        { success: false, error: 'No analysis was generated by the AI model' },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      analysis: analysisText,
      metadata: {
        imageUrl,
        customPrompt: !!prompt,
        analyzedAt: new Date().toISOString(),
      },
    })
  } catch (error) {
    console.error('POST /api/ai/analyze-image error:', error)
    const message = error instanceof Error ? error.message : 'Failed to analyze image'
    return NextResponse.json({ success: false, error: message }, { status: 500 })
  }
}
